spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

python:
  service:
    url: ${PYTHON_SERVICE_URL:http://python-ranker:7860}

server:
  port: 8080
  